# -*- coding: utf-8 -*-
"""part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FA1HyPETc-deXGNmIpnyF3fT6tgj_JQm
"""

import pandas as pd
import numpy as np
#task1 1. load the dataset:

# Public URL to the Wine Quality (Red) dataset
dataset_csv= "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"

# Note: The UCI wine dataset uses semicolons (;) as separators instead of commas
df = pd.read_csv(dataset_csv, sep=';')

print(f"Dataset Loaded successfully! Shape: {df.shape}")
print(df.head(5))
print(df.dtypes)

#2.null value analysis
null_count = df.isnull().sum()
null_percentage = (df.isnull().sum()/df.shape[0]) *100

null_analysis = pd.DataFrame({
    'Null Count': null_count,
    'Null Percentage (%)': null_percentage
})

print("--- Null Value Analysis ---")
print(null_analysis)
# Identify columns that exceed a 20% null rate
# Filter columns where the percentage is greater than 20%
high_null_cols = null_percentage[null_percentage > 20].index.tolist()

print("\n--- Columns Exceeding 20% Null Rate ---")
if high_null_cols:
    print(f"The following columns exceed the 20% threshold: {high_null_cols}")
    print("Action recommended: Consider dropping these columns or investigating data collection.")
else:
    print("No columns exceed a 20% null rate.")
# Get columns that are under or equal to the 20% threshold
low_null_cols = null_percentage[null_percentage <= 20].index

for col in low_null_cols:
# Check if the column has any nulls and is numeric
    if df[col].isnull().sum() > 0 and pd.api.types.is_numeric_dtype(df[col]):
        median_value = df[col].median()
        df[col] = df[col].fillna(median_value)
        print(f"Imputed missing values in '{col}' with median: {median_value}")

print("\nImputation complete!")

#3.Duplicate Detection anmd removal

# 1. Count duplicates before removal
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows found: {duplicate_count}")

# Capture initial row count and null percentages
initial_rows = df.shape[0]
null_perc_before = (df.isnull().sum() / initial_rows) * 100

# 2. Remove duplicates
df_cleaned = df.drop_duplicates()

# 3. Calculate and report how many rows were removed
final_rows = df_cleaned.shape[0]
rows_removed = initial_rows - final_rows
print(f"Number of rows removed: {rows_removed}")

# 4. Check if the removal changes any column's null percentage
null_perc_after = (df_cleaned.isnull().sum() / final_rows) * 100

# Break 'total_sulfur_dioxide' by introducing string anomalies to turn it into an object type
df.loc[10, 'total_sulfur_dioxide'] = 'missing_value'
df.loc[50, 'total_sulfur_dioxide'] = 'corrupted_record'

# Create a highly repetitive text column (simulating a categorical variable)
df['wine_type'] = 'Red'


# Capture memory usage before correction
initial_memory = df.memory_usage(deep=True).sum()

print("=== BEFORE DATA TYPE CORRECTION ===")
print(f"Data type of total_sulfur_dioxide: {df['total_sulfur_dioxide'].dtype}")
print(f"Data type of wine_type:            {df['wine_type'].dtype}")
print(f"Initial Deep Memory Usage:         {initial_memory:,} bytes\n")


# === DATA TYPE CORRECTION AND CLEANING ===

# Step 1: Force numeric conversion on the corrupted column
# errors='coerce' turns non-numeric text like 'missing_value' into NaN values
df['total_sulfur_dioxide'] = pd.to_numeric(df['total_sulfur_dioxide'], errors='coerce')

# Step 2: Convert the repetitive string object column to 'category'
df['wine_type'] = df['wine_type'].astype('category')


# === AFTER DATA TYPE CORRECTION ===
final_memory = df.memory_usage(deep=True).sum()
memory_saved = initial_memory - final_memory

print("=== AFTER DATA TYPE CORRECTION ===")
print(f"Data type of total_sulfur_dioxide: {df['total_sulfur_dioxide'].dtype}")
print(f"Data type of wine_type:            {df['wine_type'].dtype}")


#5.Descriptive statistics and skewness
print(df.describe())
print(df[col].skew())

#6.Outlier detection with IQR
# Columns selected for outlier analysis
target_columns = ['residual sugar', 'chlorides']

print("=== OUTLIER ANALYSIS USING THE IQR METHOD ===\n")

for col in target_columns:
    # Compute Quantiles
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1

    # Compute Bounds
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    # Identify Outliers
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_count = len(outliers)

    # Display Results
    print(f"Column: '{col}'")
    print(f"  - Q1 (25th Percentile): {q1:.4f}")
    print(f"  - Q3 (75th Percentile): {q3:.4f}")
    print(f"  - IQR:                  {iqr:.4f}")
    print(f"  - Lower Bound:          {lower_bound:.4f}")
    print(f"  - Upper Bound:          {upper_bound:.4f}")
    print(f"  - Identified Outliers:  {outlier_count} out of {len(df)} rows ({(outlier_count / len(df)) * 100:.2f}%)")
    print("-" * 45)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set style for crisp visualizations
sns.set_theme(style="whitegrid")


# Create a clean categorical variable based on quality ratings for plotting requirements
def categorize_quality(score):
    if score <= 4: return 'Low'
    elif score <= 6: return 'Medium'
    else: return 'High'

df['quality_category'] = df['quality'].apply(categorize_quality)
df['quality_category'] = pd.Categorical(df['quality_category'], categories=['Low', 'Medium', 'High'], ordered=True)


# --- VISUALIZATION 1: LINE PLOT ---
plt.figure(figsize=(10, 4))
plt.plot(df.index, df['pH'], color='teal', alpha=0.7, linewidth=1)
plt.title('Line Plot: pH Fluctuations Across Dataset Row Index', fontsize=14, pad=12)
plt.xlabel('Row Index (Sample Order)', fontsize=12)
plt.ylabel('pH Level', fontsize=12)
plt.tight_layout()
plt.show()


# --- VISUALIZATION 2: BAR CHART ---
plt.figure(figsize=(8, 5))
# Calculate the mean alcohol content for each quality group
mean_alcohol = df.groupby('quality_category', observed=False)['alcohol'].mean()
plt.bar(mean_alcohol.index, mean_alcohol.values, color=['#e74c3c', '#3498db', '#2ecc71'], edgecolor='black', alpha=0.8)
plt.title('Bar Chart: Mean Alcohol Content by Quality Category', fontsize=14, pad=12)
plt.xlabel('Wine Quality Category', fontsize=12)
plt.ylabel('Mean Alcohol Content (%)', fontsize=12)
plt.ylim(9, 12)  # Zoomed to emphasize variance differences
plt.tight_layout()
plt.show()


# --- VISUALIZATION 3: HISTOGRAM ---
plt.figure(figsize=(8, 5))
# Using 'chlorides', identified as the most skewed numeric column (skewness = 5.68)
sns.histplot(data=df, x='chlorides', bins=20, color='darkred', kde=True)
plt.title('Histogram: Distribution of Chlorides (Most Skewed Column)', fontsize=14, pad=12)
plt.xlabel('Chlorides (g/dm³)', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.tight_layout()
plt.show()


# --- VISUALIZATION 4: SCATTER PLOT ---
plt.figure(figsize=(8, 5))
# Tracking correlation between Fixed Acidity and Density
sns.scatterplot(data=df, x='fixed acidity', y='density', alpha=0.5, color='purple')
plt.title('Scatter Plot: Fixed Acidity vs. Density', fontsize=14, pad=12)
plt.xlabel('Fixed Acidity (g/dm³)', fontsize=12)
plt.ylabel('Density (g/cm³)', fontsize=12)
plt.tight_layout()
plt.show()


# --- VISUALIZATION 5: BOX PLOT ---
plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x='quality_category', y='sulphates', palette='Set2', hue='quality_category', legend=False)
plt.title('Box Plot: Sulphates Distribution Split by Quality Category', fontsize=14, pad=12)
plt.xlabel('Wine Quality Category', fontsize=12)
plt.ylabel('Sulphates (g/dm³)', fontsize=12)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



#Compute the Pearson correlation matrix
corr_matrix = df.corr(numeric_only=True)

# Render the Heat Map
plt.figure(figsize=(12, 10))
sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    square=True,
    linewidths=0.5,
    cbar_kws={"shrink": 0.8}
)
plt.title("Correlation Matrix Heat Map of Red Wine Features", fontsize=16, pad=15)
plt.tight_layout()
plt.show()

# Identify the pair with the highest absolute correlation (excluding self-correlation)
# Unstack the matrix, remove self-correlations, and grab the absolute max
corr_unstacked = corr_matrix.abs().unstack()
corr_pairs_sorted = corr_unstacked[corr_unstacked < 1.0].sort_values(ascending=False)

# Get the top pair
highest_pair = corr_pairs_sorted.index[0]
highest_val = corr_matrix.loc[highest_pair[0], highest_pair[1]]

print(f"Highest absolute correlation pair: {highest_pair[0]} and {highest_pair[1]}")
print(f"Pearson Correlation Coefficient: {highest_val:.4f}")

# Add categorical column for part (c)
def categorize_quality(score):
    if score <= 4: return 'Low'
    elif score <= 6: return 'Medium'
    else: return 'High'
df['quality_category'] = df['quality'].apply(categorize_quality)

# Inject a few random NaNs into our target columns to demonstrate imputation
np.random.seed(42)
df.loc[df.sample(5).index, 'chlorides'] = np.nan
df.loc[df.sample(5).index, 'residual sugar'] = np.nan


# ==========================================
# PART A: IMPUTATION STRATEGY COMPARISON
# ==========================================
print("=== PART A: IMPUTATION BASELINE ===")
target_cols = ['chlorides', 'residual sugar']

for col in target_cols:
    col_mean = df[col].mean()
    col_median = df[col].median()
    print(f"Column: {col:<15} | Mean: {col_mean:.4f} | Median: {col_median:.4f}")

# Imputation using Median due to heavy positive skewness
for col in target_cols:
    df[col] = df[col].fillna(df[col].median())

print(f"\nMissing values remaining:\n{df[target_cols].isnull().sum()}\n")


# ==========================================
# PART B: SPEARMAN RANK CORRELATION
# ==========================================
print("=== PART B: CORRELATION COMPARISON ===")
# Drop categorical column for matrix math
numeric_df = df.select_dtypes(include=[np.number])

pearson_mat = numeric_df.corr(method='pearson')
spearman_mat = numeric_df.corr(method='spearman')

# Calculate absolute differences
diff_mat = (spearman_mat - pearson_mat).abs()

# Extract unique pairs (lower triangle) to find top differences
upper_tri = diff_mat.where(np.triu(np.ones(diff_mat.shape), k=1).astype(bool))
diff_pairs = upper_tri.unstack().dropna().sort_values(ascending=False)

print("\nTop 3 Pairs with Largest Absolute Difference |Spearman - Pearson|:")
print(f"1. {diff_pairs.index[0]}: {diff_pairs.iloc[0]:.4f}")
print(f"2. {diff_pairs.index[1]}: {diff_pairs.iloc[1]:.4f}")
print(f"3. {diff_pairs.index[2]}: {diff_pairs.iloc[2]:.4f}\n")


# ==========================================
# PART C: GROUPED AGGREGATION
# ==========================================
print("=== PART C: GROUPED AGGREGATION ===")
grouped_stats = df.groupby('quality_category', observed=False)['alcohol'].agg(['mean', 'std', 'count'])
print(grouped_stats)

# Calculate ratio
max_mean = grouped_stats['mean'].max()
min_mean = grouped_stats['mean'].min()
print(f"\nRatio of Highest to Lowest Group Mean: {max_mean / min_mean:.4f}")